# Generated by Django 2.2.5 on 2019-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50, null=True)),
                ('car_model', models.CharField(max_length=50, null=True)),
                ('car_color', models.CharField(max_length=50, null=True)),
                ('car_immat', models.CharField(max_length=10, null=True, unique=True)),
                ('car_total_seats', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
