# Generated by Django 2.2.5 on 2019-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_street', models.CharField(max_length=50)),
                ('departure_city', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
                ('departure_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
