# Generated by Django 2.2.5 on 2019-09-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='car',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
            preserve_default=False,
        ),
    ]
