# Generated by Django 2.2.5 on 2019-09-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='car',
        ),
    ]
